services:
    Rector\Rector\Class_\ClassReplacerRector:
        $oldToNewClasses:
            # see https://twig.symfony.com/doc/1.x/deprecated.html#filters
            Twig_SimpleFilter: 'Twig_Filter'
            # see https://twig.symfony.com/doc/1.x/deprecated.html#functions
            Twig_SimpleFunction: 'Twig_Function'
