services:
    Rector\Rector\MethodCall\RenameMethodRector:
         'Twig_Node':
             'getLine': 'getTemplateLine'
             'getFilename': 'getTemplateName'
         'Twig_Template':
             'getSource': 'getSourceContext'
         'Twig_Error':
             'getTemplateFile': 'getTemplateName'
             'getTemplateName': 'setTemplateName'
