# see: https://gnugat.github.io/2015/09/23/phpunit-with-phpspec.html
services:
    Rector\PhpSpecToPHPUnit\Rector\Class_\PhpSpecClassToPHPUnitClassRector: ~
    Rector\PhpSpecToPHPUnit\Rector\RenameSpecFileToTestFileRector: ~