services:
    Rector\Symfony\Rector\Validator\ConstraintUrlOptionRector: ~
    Rector\Symfony\Rector\Form\FormIsValidRector: ~
    Rector\Symfony\Rector\Form\StringFormTypeToClassRector: ~
    Rector\Symfony\Rector\VarDumper\VarDumperTestTraitMethodArgsRector: ~
    Rector\Symfony\Rector\DependencyInjection\ContainerBuilderCompileEnvArgumentRector: ~

    Rector\Symfony\Rector\Process\ProcessBuilderInstanceRector: ~
    Rector\Symfony\Rector\Process\ProcessBuilderGetProcessRector: ~

    Rector\Renaming\Rector\Class_\RenameClassRector:
        $oldToNewClasses:
            'Symfony\Component\Validator\Tests\Constraints\AbstractConstraintValidatorTest': 'Symfony\Component\Validator\Test\ConstraintValidatorTestCase'
            'Symfony\Component\Process\ProcessBuilder': 'Symfony\Component\Process\Process'
