services:
    Rector\PHPStan\Rector\Cast\RecastingRemovalRector: ~
    Rector\PHPStan\Rector\Assign\PHPStormVarAnnotationRector: ~
    Rector\PHPStan\Rector\Node\RemoveNonExistingVarAnnotationRector: ~
