# See https://github.com/shopware/shopware/blob/5.6/UPGRADE-5.6.md
services:
    Rector\Shopware\Rector\MethodCall\ReplaceEnlightResponseWithSymfonyResponseRector: ~
    Rector\Rector\MethodCall\RenameMethodRector:
        Enlight_Controller_Response_Response:
            getHttpResponseCode: getStatusCode
            setHttpResponseCode: setStatusCode
            sendCookies: sendHeaders
            setBody: setContent
