services:
    Rector\Rector\Architecture\DependencyInjection\ActionInjectionToConstructorInjectionRector: null
    Rector\Rector\Architecture\DependencyInjection\ReplaceVariableByPropertyFetchRector: null
