services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Rector\Utils\DocumentationGenerator\:
        resource: '../src'
        exclude: '../src/{Exception,Configuration/Configuration.php,Node/*Info.php}'
