imports:
    # in monorepo
    - { resource: '../../../../vendor/symplify/better-phpdoc-parser/src/config/services.yml',  ignore_errors: true }
    # as dependency
    - { resource: '../../../../../../symplify/better-phpdoc-parser/src/config/services.yml', ignore_errors: true }

services:
    Rector\BetterPhpDocParser\:
        resource: '../'
