services:
    # <> → !=
    Rector\Celebrity\Rector\NotEqual\CommonNotEqualRector: ~

    Rector\Renaming\Rector\Function_\RenameFunctionRector:
        split: 'explode'
        join: 'implode'
        sizeof: 'count'

    # settype($value, 'int') → (int) $value
    Rector\Celebrity\Rector\FuncCall\SetTypeToCastRector: ~

    # class { var $value; } → class { public $value; }
    Rector\Php52\Rector\Property\VarToPublicPropertyRector: ~pu


    #  false or true → false || true
    #  false and true → false && true
    Rector\Celebrity\Rector\BooleanOp\LogicalToBooleanRector: ~
