services:
    Rector\NetteToSymfony\Rector\ClassMethod\RenameEventNamesInEventSubscriberRector: ~
    Rector\NetteToSymfony\Rector\MethodCall\FromHttpRequestGetHeaderToHeadersGetRector: ~
    Rector\NetteToSymfony\Rector\MethodCall\FromRequestGetParameterToAttributesGetRector: ~
    Rector\NetteToSymfony\Rector\ClassMethod\RouterListToControllerAnnotationsRector: ~
