services:
    _defaults:
        autowire: true
        public: true # for tests

    Rector\NodeTraverserQueue\:
        resource: '../../src'
        exclude: '../../src/{Exception}'

    PhpParser\NodeFinder: ~
