services:
    _defaults:
        autowire: true
        public: true # for tests

    Rector\NodeTraverserQueue\:
        resource: '../'
        exclude: '../{Exception}'

    PhpParser\NodeFinder: ~
