services:
    Rector\CodingStyle\Rector\If_\NullableCompareToNullRector: ~
    Rector\CodingStyle\Rector\ClassConst\CompleteVarDocTypeConstantRector: ~
    Rector\CodingStyle\Rector\FuncCall\SimpleArrayCallableToStringRector: ~
    Rector\CodingStyle\Rector\Identical\IdenticalFalseToBooleanNotRector: ~
    Rector\CodingStyle\Rector\Switch_\BinarySwitchToIfElseRector: ~
    Rector\CodingStyle\Rector\FuncCall\ConsistentImplodeRector: ~
    Rector\CodingStyle\Rector\FuncCall\SetTypeToCastRector: ~
    Rector\CodingStyle\Rector\Use_\RemoveUnusedAliasRector: ~

    # requires configuration
    # Rector\CodingStyle\Rector\ClassMethod\YieldClassMethodToArrayClassMethodRector: ~
