services:
    Rector\CodingStyle\Rector\If_\NullableCompareToNullRector: ~
    Rector\CodingStyle\Rector\ClassConst\CompleteVarDocTypeConstantRector: ~
    Rector\CodingStyle\Rector\FuncCall\SimpleArrayCallableToStringRector: ~
    Rector\CodingStyle\Rector\Identical\IdenticalFalseToBooleanNotRector: ~
    Rector\CodingStyle\Rector\Switch_\BinarySwitchToIfElseRector: ~
    Rector\CodingStyle\Rector\FuncCall\ConsistentImplodeRector: ~
    Rector\CodingStyle\Rector\Use_\RemoveUnusedAliasRector: ~

    # requires configuration
    # Rector\CodingStyle\Rector\ClassMethod\YieldClassMethodToArrayClassMethodRector: ~
    # Rector\CodingStyle\Rector\ClassMethod\ReturnArrayClassMethodToYieldRector: ~
    Rector\CodingStyle\Rector\String_\SymplifyQuoteEscapeRector: ~
    Rector\CodingStyle\Rector\ClassConst\SplitGroupedConstantsAndPropertiesRector: ~
    Rector\CodingStyle\Rector\String_\SplitStringClassConstantToClassConstFetchRector: ~
    Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector: ~

    # 'ClassName' → ClassName::class
    Rector\Php\Rector\String_\StringClassNameToClassConstantRector: ~
    Rector\CodingStyle\Rector\FuncCall\ConsistentPregDelimiterRector: ~
