services:
    _defaults:
        autowire: true
        public: true # for tests

    Rector\BetterReflection\:
        resource: '../../src'

    # nikic\PHP-Parser
    Rector\BetterReflection\SourceLocator\Ast\Locator: ~
