services:
    _defaults:
        autowire: true

    Rector\BetterReflection\:
        resource: '../'

    # nikic\PHP-Parser
    Roave\BetterReflection\SourceLocator\Ast\Locator: ~

    phpDocumentor\Reflection\FqsenResolver: ~
