services:
    # <> → !=
    Rector\Celebrity\Rector\NotEqual\CommonNotEqualRector: ~

    Rector\Rector\Function_\FunctionReplaceRector:
        split: 'explode'
        join: 'implode'

    # settype($value, 'int') → (int) $value
    Rector\Celebrity\Rector\FuncCall\SetTypeToCastRector: ~

    # class { var $value; } → class { public $value; }
    Rector\Php\Rector\Property\VarToPublicPropertyRector: ~

    #  false or true → false || true
    #  false and true → false && true
    Rector\Celebrity\Rector\BooleanOp\LogicalToBooleanRector: ~
