services:
    # <> → !=
    Rector\Celebrity\Rector\NotEqual\CommonNotEqualRector: ~

    Rector\Rector\Function_\FunctionReplaceRector:
        split: 'explode'
        join: 'implode'

    # settype($value, 'int') → (int) $value
    Rector\Celebrity\Rector\FuncCall\SetTypeToCastRector: ~
