imports:
    - { resource: 'phpunit-exception.yaml' }

services:
    Rector\Renaming\Rector\Annotation\RenameAnnotationRector:
        PHPUnit\Framework\TestCase:
            scenario: 'test'
    Rector\PHPUnit\Rector\Class_\RemoveDataProviderTestPrefixRector: ~
