services:
    # see https://github.com/sebastianbergmann/phpunit-mock-objects/issues/137
    Rector\Renaming\Rector\MethodCall\RenameMethodRector:
        $oldToNewMethodsByClass:
            'PHPUnit_Framework_MockObject_MockObject':
                staticExpects: 'expects'
