services:
    Rector\PHPUnit\Rector\MethodCall\RemoveExpectAnyFromMockRector: ~
    Rector\PHPUnit\Rector\Class_\AddSeeTestAnnotationRector: ~

    # [configurable]
    # Rector\PHPUnit\Rector\Class_\ArrayArgumentInTestToDataProviderRector: ~
