services:
    Rector\PHPUnit\Rector\MethodCall\RemoveExpectAnyFromMockRector: ~
    Rector\PHPUnit\Rector\Class_\AddSeeTestAnnotationRector: ~
    Rector\PHPUnit\Rector\Class_\ArrayArgumentInTestToDataProviderRector: ~
