services:
    # handles 2nd and 3rd argument of setExpectedException
    Rector\PHPUnit\Rector\DelegateExceptionArgumentsRector: ~

    # @expectedException → $this->expectException()
    Rector\PHPUnit\Rector\ExceptionAnnotationRector: ~

    Rector\Rector\MethodCall\RenameMethodRector:
        PHPUnit\Framework\TestClass:
            setExpectedException: 'expectedException'
            setExpectedExceptionRegExp: 'expectedException'
