services:
    # handles 2nd and 3rd argument of setExpectedException
    Rector\PHPUnit\Rector\DelegateExceptionArgumentsRector: ~

    # @expectedException → $this->expectException()
    Rector\PHPUnit\Rector\ExceptionAnnotationRector: ~

    Rector\Renaming\Rector\MethodCall\RenameMethodRector:
        $oldToNewMethodsByClass:
            PHPUnit\Framework\TestClass:
                setExpectedException: 'expectedException'
                setExpectedExceptionRegExp: 'expectedException'
