services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Rector\PSR4\:
        resource: '../src'
        exclude:
            - '../src/Rector/**/*Rector.php'
            - '../src/ValueObject/*'
