parameters:
    # PHP 7.2 "object" type hint
    enable_object_type: true

services:
    Rector\Php72\Rector\Each\WhileEachToForeachRector: ~
    Rector\Php72\Rector\Each\ListEachRector: ~
    Rector\Php72\Rector\Unset_\UnsetCastRector: ~
    Rector\Php72\Rector\ConstFetch\BarewordStringRector: ~

    Rector\Renaming\Rector\Function_\RenameFunctionRector:
        $oldFunctionToNewFunction:
            jpeg2wbmp: 'imagecreatefromjpeg' # and imagewbmp
            png2wbmp: 'imagecreatefrompng' # or imagewbmp
            # http://php.net/manual/en/migration72.deprecated.php#migration72.deprecated.gmp_random-function
            gmp_random: 'gmp_random_bits' # or gmp_random_range
            read_exif_data: 'exif_read_data'

    Rector\Php72\Rector\FuncCall\GetClassOnNullRector: ~
    Rector\Php72\Rector\FuncCall\IsObjectOnIncompleteClassRector: ~
    Rector\Php72\Rector\FuncCall\ParseStrWithResultArgumentRector: ~
    Rector\Php72\Rector\FuncCall\StringsAssertNakedRector: ~
    Rector\Php72\Rector\FuncCall\CreateFunctionToAnonymousFunctionRector: ~
    Rector\Php72\Rector\FuncCall\StringifyDefineRector: ~
