imports:
    - { resource: "../database-migration/mysql-to-mysqli.yaml" }

services:
    Rector\Php70\Rector\FunctionLike\Php4ConstructorRector: ~
    Rector\Php70\Rector\Ternary\TernaryToNullCoalescingRector: ~
    Rector\Php70\Rector\FuncCall\RandomFunctionRector: ~
    Rector\Php70\Rector\FunctionLike\ExceptionHandlerTypehintRector: ~
    Rector\Php70\Rector\FuncCall\MultiDirnameRector: ~
    Rector\Php70\Rector\List_\ListSplitStringRector: ~
    Rector\Php70\Rector\List_\EmptyListRector: ~

    # be careful, run this just once, since it can keep swapping order back and forth
    Rector\Php70\Rector\List_\ListSwapArrayOrderRector: ~

    Rector\Php70\Rector\FuncCall\CallUserMethodRector : ~
    Rector\Php70\Rector\FuncCall\EregToPregMatchRector: ~
    Rector\Php70\Rector\Switch_\ReduceMultipleDefaultSwitchRector: ~
    Rector\Php70\Rector\Ternary\TernaryToSpaceshipRector: ~
    Rector\Php70\Rector\If_\IfToSpaceshipRector: ~
    Rector\Php70\Rector\StaticCall\StaticCallOnNonStaticToInstanceCallRector: ~
    Rector\Php70\Rector\MethodCall\ThisCallOnStaticMethodToStaticCallRector: ~

    Rector\Php70\Rector\Break_\BreakNotInLoopOrSwitchToReturnRector: ~
    Rector\Php70\Rector\FuncCall\RenameMktimeWithoutArgsToTimeRector: ~
