services:
    Rector\Php71\Rector\BinaryOp\IsIterableRector: ~

    Rector\Php\Rector\Name\ReservedObjectRector:
        $reservedKeywordsToReplacements:
            Object: 'BaseObject'

    Rector\Php71\Rector\TryCatch\MultiExceptionCatchRector: ~
    Rector\Php71\Rector\Assign\AssignArrayToStringRector: ~
    Rector\Php71\Rector\FuncCall\CountOnNullRector: ~
    Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector: ~
    Rector\Php71\Rector\BinaryOp\BinaryOpBetweenNumberAndStringRector: ~
