services:
    Rector\Php\Rector\BinaryOp\IsCountableRector: ~
    Rector\Php\Rector\FuncCall\ArrayKeyFirstLastRector: ~
    Rector\Php\Rector\FuncCall\SensitiveDefineRector: ~
    Rector\Php\Rector\ConstFetch\SensitiveConstantNameRector: ~
    Rector\Php\Rector\String\SensitiveHereNowDocRector: ~

    Rector\Rector\Function_\FunctionReplaceRector:
        mbregex_encoding: 'mb_regex_encoding'
        mbereg: 'mb_ereg'
        mbereg_replace: 'mb_ereg_replace'
        mberegi_replace: 'mb_eregi_replace'
        mbsplit: 'mb_split'
        mbereg_match: 'mb_ereg_match'
        mbereg_search: 'mb_ereg_search'
        mbereg_search_pos: 'mb_ereg_search_pos'
        mbereg_search_regs: 'mb_ereg_search_regs'
        mbereg_search_init: 'mb_ereg_search_init'
        mbereg_search_getregs: 'mb_ereg_search_getregs'
        mbereg_search_getpos: 'mb_ereg_search_getpos'
        mbereg_search_setpos: 'mb_ereg_search_setpos'

    Rector\Php\Rector\FuncCall\StringifyStrNeedlesRector: ~
    Rector\Php\Rector\FuncCall\JsonThrowOnErrorRector: ~
