services:
    Rector\Php\Rector\FunctionLike\Php4ConstructorRector: ~
    Rector\Php\Rector\Ternary\TernaryToNullCoalescingRector: ~
    Rector\Php\Rector\FuncCall\RandomFunctionRector: ~
    Rector\Php\Rector\FunctionLike\ExceptionHandlerTypehintRector: ~
    Rector\Php\Rector\FuncCall\MultiDirnameRector: ~
    Rector\Php\Rector\List_\ListSplitStringRector: ~
