services:
    Rector\Php\Rector\Property\TypedPropertyRector: ~

    Rector\Rector\Function_\FunctionReplaceRector:
        # https://wiki.php.net/rfc/deprecations_php_7_4#the_real_type
        is_float: 'is_real'
        # https://wiki.php.net/rfc/deprecations_php_7_4#apache_request_headers_function
        apache_request_headers: 'getallheaders'
        hebrevc: ['nl2br', 'hebrev']
    Rector\Php\Rector\FuncCall\ArrayKeyExistsOnPropertyRector: ~
    Rector\Php\Rector\FuncCall\FilterVarToAddSlashesRector: ~
    Rector\Php\Rector\StaticCall\ExportToReflectionFunctionRector: ~
    Rector\Php\Rector\MagicConstClass\ClassConstantToSelfClassRector: ~
    Rector\Php\Rector\FuncCall\GetCalledClassToStaticClassRector: ~
    Rector\Php\Rector\FuncCall\MbStrrposEncodingArgumentPositionRector: ~
    Rector\Php\Rector\Double\RealToFloatTypeCastRector: ~
