services:
    Rector\Php\Rector\BinaryOp\IsIterableRector: ~
    Rector\Php\Rector\Name\ReservedObjectRector:
        Object: 'BaseObject'

    Rector\Php\Rector\TryCatch\MultiExceptionCatchRector: ~
    Rector\Php\Rector\Assign\AssignArrayToStringRector: ~
    Rector\Php\Rector\FuncCall\CountOnNullRector: ~
