parameters:
    doctrine_uuid_generator_class: 'Ramsey\Uuid\Doctrine\UuidGenerator'

services:
    _defaults:
        autowire: true
        public: true

    Rector\Doctrine\:
        resource: '../src'
        exclude: '../src/{Rector/**/*Rector.php,ValueObject/*}'
