services:
    Rector\SOLID\Rector\Class_\FinalizeClassesWithoutChildrenRector: ~

    Rector\SOLID\Rector\ClassConst\PrivatizeLocalClassConstantRector: ~
    Rector\SOLID\Rector\Class_\MakeUnusedClassesWithChildrenAbstractRector: ~
