services:
    Rector\Rector\Dynamic\ParentTypehintedArgumentRector:
        $typehintForArgumentByMethodAndClass:
            'Doctrine\ORM\Mapping\ClassMetadataFactory':
                'setEntityManager':
                    'em': 'Doctrine\ORM\EntityManagerInterface'
            'Doctrine\ORM\Tools\DebugUnitOfWorkListener':
                'dumpIdentityMap':
                    'em': 'Doctrine\ORM\EntityManagerInterface'

    Rector\Rector\Dynamic\ArgumentRemoverRector:
        $argumentChangesByMethodAndType:
            -
                class: 'Doctrine\ORM\Persisters\Entity\AbstractEntityInheritancePersister'
                method: 'getSelectJoinColumnSQL'
                position: 4

