services:
    # differ
    diffOutputBuilder:
        class: SebastianBergmann\Diff\Output\StrictUnifiedDiffOutputBuilder
        arguments:
            $options:
                'fromFile': 'Original'
                'toFile': 'New'

    differ:
        class: SebastianBergmann\Diff\Differ
        arguments:
            - '@diffOutputBuilder'

    # makrdown differ
    markdownDiffOutputBuilder:
        class: SebastianBergmann\Diff\Output\UnifiedDiffOutputBuilder
        arguments:
            $header: ''

    markdownDiffer:
        class: SebastianBergmann\Diff\Differ
        arguments:
            - '@markdownDiffOutputBuilder'
