services:
    _defaults:
        autowire: true

    Rector\ConsoleDiffer\:
        resource: ..

    SebastianBergmann\Diff\Output\UnifiedDiffOutputBuilder:

    SebastianBergmann\Diff\Differ:
        arguments:
            - '@SebastianBergmann\Diff\Output\UnifiedDiffOutputBuilder'
