services:
    _defaults:
        autowire: true

    Rector\ConsoleDiffer\:
        resource: ..

    SebastianBergmann\Diff\Output\StrictUnifiedDiffOutputBuilder:
        arguments:
            $options:
                'fromFile': 'Original'
                'toFile': 'New'

    SebastianBergmann\Diff\Differ:
        arguments:
            - '@SebastianBergmann\Diff\Output\StrictUnifiedDiffOutputBuilder'
