imports:
    - { resource: 'external-services.yml' }

services:
    _defaults:
        autowire: true

    Rector\ConsoleDiffer\:
        resource: ..

    Rector\ConsoleDiffer\DifferAndFormatter:
        $differ: '@differ'

    Rector\ConsoleDiffer\MarkdownDifferAndFormatter:
        $markdownDiffer: '@markdownDiffer'
