# version gedmo/doctrine-extensions 2.x to knplabs/doctrine-behaviors 2.0
services:
    Rector\DoctrineGedmoToKnplabs\Rector\Class_\TimestampableBehaviorRector: null
    Rector\DoctrineGedmoToKnplabs\Rector\Class_\SluggableBehaviorRector: null
    Rector\DoctrineGedmoToKnplabs\Rector\Class_\TreeBehaviorRector: ~
    Rector\DoctrineGedmoToKnplabs\Rector\Class_\TranslationBehaviorRector: ~
