# source: https://book.cakephp.org/3.0/en/appendices/3-8-migration-guide.html

services:
    Rector\Rector\MethodCall\RenameMethodRector:
        Cake\ORM\Entity:
            'visibleProperties': 'getVisible'
