services:
    Rector\Rector\Typehint\ParentTypehintedArgumentRector:
        $typehintForArgumentByMethodAndClass:
            Doctrine\ORM\Mapping\ClassMetadataFactory:
                setEntityManager:
                    em: 'Doctrine\ORM\EntityManagerInterface'
            Doctrine\ORM\Tools\DebugUnitOfWorkListener:
                dumpIdentityMap:
                    em: 'Doctrine\ORM\EntityManagerInterface'

    Rector\Rector\Argument\ArgumentRemoverRector:
        $positionsByMethodNameByClassType:
            Doctrine\ORM\Persisters\Entity\AbstractEntityInheritancePersister:
                getSelectJoinColumnSQL:
                     4: ~
