services:
    # first, run these rules
    Rector\Doctrine\Rector\Class_\AddUuidToEntityWhereMissingRector: ~
    Rector\Doctrine\Rector\Class_\AddUuidMirrorForRelationPropertyRector: ~

    # then run this to validate the change: bin/console doctrine:schema:update --dump-sql
