services:
    # first, run these rule → then look at step-1
    Rector\Doctrine\Rector\Class_\AddUuidToEntityWhereMissingRector: ~
    Rector\Doctrine\Rector\Class_\AddUuidMirrorForRelationPropertyRector: ~
    Rector\Doctrine\Rector\Class_\AlwaysInitializeUuidInEntityRector: ~
