services:
    # properties
    Rector\Doctrine\Rector\Property\AddUuidAnnotationsToIdPropertyRector: ~
    Rector\Doctrine\Rector\Property\RemoveTemporaryUuidColumnPropertyRector: ~
    Rector\Doctrine\Rector\Property\RemoveTemporaryUuidRelationPropertyRector: ~

    # methods
    Rector\Doctrine\Rector\ClassMethod\ChangeGetIdTypeToUuidRector: ~
    Rector\Doctrine\Rector\ClassMethod\ChangeSetIdTypeToUuidRector: ~
