rectors:
    Rector\Rector\Dynamic\ParentTypehintedArgumentRector:
        'Doctrine\ORM\Mapping\ClassMetadataFactory':
            'setEntityManager':
                'em': 'Doctrine\ORM\EntityManagerInterface'
        'Doctrine\ORM\Tools\DebugUnitOfWorkListener':
            'dumpIdentityMap':
                'em': 'Doctrine\ORM\EntityManagerInterface'

    Rector\Rector\Dynamic\ArgumentReplacerRector:
        -
            class: 'Doctrine\ORM\Persisters\Entity\AbstractEntityInheritancePersister'
            method: 'getSelectJoinColumnSQL'
            position: 4
            type: 'removed'
