services:
    Rector\PhpParser\Rector\IdentifierRector: ~
    Rector\PhpParser\Rector\ParamAndStaticVarNameRector: ~
    Rector\PhpParser\Rector\CatchAndClosureUseNameRector: ~
    Rector\PhpParser\Rector\SetLineRector: ~
    Rector\PhpParser\Rector\RemoveNodeRector: ~
    Rector\PhpParser\Rector\UseWithAliasRector: ~

    Rector\Rector\Property\RenamePropertyRector:
        'PhpParser\Node\Stmt\Class_':
            'type': 'flags'
        'PhpParser\Node\Stmt\ClassMethod':
            'type': 'flags'
        'PhpParser\Node\Stmt\Property':
            'type': 'flags'

    Rector\Rector\Constant\RenameClassConstantRector:
        'PhpParser\Node\Stmt\Class_':
            'VISIBILITY_MODIFER_MASK': 'VISIBILITY_MODIFIER_MASK'

    Rector\Rector\Class_\RenameClassRector:
        'PhpParser\BuilderAbstract': 'PhpParser\Builder'
