# source: https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html

services:
    Rector\CakePHP\Rector\MethodCall\ModalToGetSetRector:
        $methodNamesByTypes:
            Cake\Core\InstanceConfigTrait:
                - 'config'
            Cake\Core\StaticConfigTrait:
                - 'config'
                - 'dsnClassMap'
            Cake\Console\ConsoleOptionParser:
                - 'command'
                - 'description'
                - 'epilog'
            Cake\Database\Connection:
                - 'driver'
                - 'schemaCollection'
                #- 'useSavePoints' #() (now enableSavePoints()/isSavePointsEnabled('
            Cake\Database\Driver:
                - 'autoQuoting' # (now enableAutoQuoting()/isAutoQuotingEnabled('
            Cake\Database\Expression\FunctionExpression:
                - 'name'
            #Cake\Database\Expression\QueryExpression:
                #- 'tieWith' #() (now setConjunction()/getConjunction('
            Cake\Database\Expression\ValuesExpression:
                - 'columns'
                - 'values'
                - 'query'
            Cake\Database\Query:
                - 'connection'
                - 'selectTypeMap'
                #- 'bufferResults' #() (now enableBufferedResults()/isBufferedResultsEnabled('
            Cake\Database\Schema\CachedCollection:
                - 'cacheMetadata'
            Cake\Database\Schema\TableSchema:
                - 'options'
                #- 'temporary' #() (now setTemporary()/isTemporary('
            Cake\Database\TypeMap:
                - 'defaults'
                - 'types'
            Cake\Database\TypeMapTrait:
                - 'typeMap'
                - 'defaultTypes'
            Cake\ORM\Association:
                - 'name'
                - 'cascadeCallbacks'
                - 'source'
                - 'target'
                - 'conditions'
                - 'bindingKey'
                - 'foreignKey'
                - 'dependent'
                - 'joinType'
                - 'property'
                - 'strategy'
                - 'finder'
            Cake\ORM\Association\BelongsToMany:
                - 'targetForeignKey'
                - 'saveStrategy'
                - 'conditions'
            Cake\ORM\Association\HasMany:
                - 'saveStrategy'
                - 'foreignKey'
                - 'sort'
            Cake\ORM\Association\HasOne:
                - 'foreignKey'
            Cake\ORM\EagerLoadable:
                - 'config'
                #- 'setter part of canBeJoined() (now setCanBeJoined('
#            Cake\ORM\EagerLoader:
                #- 'matching' #() (getMatching() will have to be called after setMatching() to keep the old behavio'
                #- 'autoFields' #() (now enableAutoFields()/isAutoFieldsEnabled('
            Cake\ORM\Locator\TableLocator:
                - 'config'
            Cake\ORM\Query:
                - 'eagerLoader'
                #- 'hydrate' #() (now enableHydration()/isHydrationEnabled('
                #- 'autoFields' #() (now enableAutoFields()/isAutoFieldsEnabled('
            Cake\ORM\Table:
                - 'table'
                - 'alias'
                - 'registryAlias'
                - 'connection'
                - 'schema'
                - 'primaryKey'
                - 'displayField'
                - 'entityClass'
            Cake\Mailer\Email:
                - 'from'
                - 'sender'
                - 'replyTo'
                - 'readReceipt'
                - 'returnPath'
                - 'to'
                - 'cc'
                - 'bcc'
                - 'charset'
                - 'headerCharset'
                - 'emailPattern'
                - 'subject'
                #- 'template() (now setTemplate()/getTemplate() and setLayout()/getLayout('
                #- 'viewRender() (now setViewRenderer()/getViewRenderer('
                - 'viewVars'
                - 'theme'
                - 'helpers'
                - 'emailFormat'
                - 'transport'
                - 'messageId'
                - 'domain'
                - 'attachments'
                - 'configTransport'
                - 'profile'
            Cake\Validation\Validator:
                - 'provider'
            Cake\View\StringTemplateTrait:
                - 'templates'
            Cake\View\ViewBuilder:
                - 'templatePath'
                - 'layoutPath'
                - 'plugin'
                - 'helpers'
                - 'theme'
                - 'template'
                - 'layout'
                - 'options'
                - 'name'
                - 'className'
                #- 'autoLayout' #() (now enableAutoLayout()/isAutoLayoutEnabled('

    Rector\Rector\MethodCall\MethodNameReplacerRector:
        $perClassOldToNewMethods:
            Cake\Network\Request:
                param: 'getParam'
                data: 'getData'
                query: 'getQuery'
                cookie: 'getCookie'
                method: 'getMethod'
                setInput: 'withBody'

            Cake\Network\Response:
                location: 'withLocation'
                disableCache: 'withDisabledCache'
                type: 'withType'
                charset: 'withCharset'
                cache: 'withCache'
                modified: 'withModified'
                expires: 'withExpires'
                sharable: 'withSharable'
                maxAge: 'withMaxAge'
                vary: 'withVary'
                etag: 'withEtag'
                compress: 'withCompression'
                length: 'withLength'
                mustRevalidate: 'withMustRevalidate'
                notModified: 'withNotModified'
                cookie: 'withCookie'
                file: 'withFile'
                download: 'withDownload'

            Cake\Event\Event:
                'name': 'getName'
                'subject': 'getSubject'
                'result': 'getResult'
                'data': 'getData'

            Cake\View\Helper\FormHelper:
                input: 'control'
                inputs: 'controls'
                allInputs: 'allControls'
