# source: https://book.cakephp.org/3.0/en/appendices/3-5-migration-guide.html

services:
    Rector\Rector\Property\PropertyToMethodRector:
        $perClassPropertyToMethods:
            'Cake\Network\Request':
                'params':
                    'get':
                        method: 'getAttribute'
                        arguments:
                            - 'params'
                'data':
                    'get': 'getData'
                'query':
                    'get': 'getQueryParams'
                'cookies':
                    'get': 'getCookie'
                'base':
                    'get':
                        method: 'getAttribute'
                        arguments:
                            - 'base'
                'webroot':
                    'get':
                        method: 'getAttribute'
                        arguments:
                            - 'webroot'

    Rector\Rector\Class_\ClassReplacerRector:
        $oldToNewClasses:
            'Cake\Http\Client\CookieCollection ': 'Cake\Http\Cookie\CookieCollection'

    Rector\Rector\Property\PropertyNameReplacerRector:
        $perClassOldToNewProperties:
            'Cake\Network\Request':
                '_session': 'session'
