services:
    # dependency-injection
    Rector\Rector\Argument\ArgumentAdderRector:
        Symfony\Component\DependencyInjection\ContainerBuilder:
            addCompilerPass:
                2:
                    name: 'priority'
                    default_value: 0
