services:
    # yaml
    # covers https://github.com/symfony/symfony/pull/24523
    Rector\Symfony\Rector\Yaml\SessionStrictTrueByDefaultYamlRector: ~

    Rector\YamlRector\Rector\ReplaceStringYamlRector:
        ' !php/object:': ' !php/object '
        ' !php/const:': ' !php/const '
        ' !str': ' !!str'

    Rector\Rector\Argument\ArgumentRemoverRector:
        Symfony\Component\Yaml\Yaml:
            parse:
                2:
                    - 'Symfony\Component\Yaml\Yaml::PARSE_KEYS_AS_STRINGS'
