services:
    Rector\Rector\Class_\ClassReplacerRector:
        # https://github.com/symfony/symfony/commit/a7e319d9e1316e2e18843f8ce15b67a8693e5bf9
        Symfony\Bundle\FrameworkBundle\Controller\Controller: 'Symfony\Bundle\FrameworkBundle\Controller\AbstractController'

    # https://symfony.com/blog/new-in-symfony-4-2-important-deprecations
    Rector\Symfony\Rector\New_\StringToArrayArgumentProcessRector: ~
    Rector\Symfony\Rector\New_\RootNodeTreeBuilderRector: ~

    Rector\Rector\MethodCall\MethodNameReplacerRector:
        # https://github.com/symfony/symfony/commit/463f986c28a497571967e37c1314e9911f1ef6ba
        Symfony\Component\Console\Helper\TableStyle:
            setHorizontalBorderChar: 'setHorizontalBorderChars'
            setVerticalBorderChar: 'setVerticalBorderChars'
            # special case to "getVerticalBorderChar" → "getBorderChars()[3]"
            getVerticalBorderChar:
                name: 'getBorderChars'
                array_key: 3
            getHorizontalBorderChar:
                name: 'getBorderChars'
                array_key: 2
