services:
    # yaml
    Rector\YamlRector\Rector\ReplaceStringYamlRector:
        $oldToNewString:
            # https://github.com/symfony/symfony/pull/17462
            ' !!php/object': ' !php/object'

    # replace args
    Rector\Rector\Dynamic\ArgumentDefaultValueReplacerRector:
        $argumentChangesByMethodAndType:
            # covers https://github.com/symfony/symfony/blob/3.4/UPGRADE-3.1.md#yaml
            -
                class: 'Symfony\Component\Yaml\Yaml'
                method: 'parse'
                position: 1
                replacement:
                    'true': 'Symfony\Component\Yaml\Yaml::PARSE_EXCEPTION_ON_INVALID_TYPE'
                    'false': 0
