services:
    # yaml
    # covers https://github.com/symfony/symfony/blob/3.4/UPGRADE-3.2.md#yaml
    Rector\Symfony\Rector\Yaml\SpaceBetweenKeyAndValueYamlRector: ~

    # dependency-injection
    Rector\Rector\Dynamic\ArgumentAdderRector:
        $argumentChangesByMethodAndType:
            -
                class: Symfony\Component\DependencyInjection\ContainerBuilder
                method: addCompilerPass
                position: 2
                default_value: 0
