services:
    # yaml
    Rector\YamlRector\Rector\ReplaceStringYamlRector:
        $oldToNewString:
            # covers https://github.com/symfony/symfony/pull/17462/files
            '!!php/object': '!php/object'
            '!php/object:': '!php/object '
