services:
    Rector\Symfony\Rector\BinaryOp\ResponseStatusCodeRector: ~
    Rector\CodeQuality\Rector\Identical\BooleanNotIdenticalToNotIdenticalRector: ~
    Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector: ~
