services:
    # https://symfony.com/blog/new-in-symfony-4-2-important-deprecations
    Rector\Symfony\Rector\New_\StringToArrayArgumentProcessRector: ~
    Rector\Symfony\Rector\New_\RootNodeTreeBuilderRector: ~
