services:
    # https://symfony.com/blog/new-in-symfony-4-3-better-test-assertions
    Rector\Symfony\Rector\MethodCall\SimplifyWebTestCaseAssertionsRector: ~

    # https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching
    Rector\Rector\Class_\RenameClassRector:
        Symfony\Component\HttpKernel\Event\FilterControllerArgumentsEvent: 'Symfony\Component\HttpKernel\Event\ControllerArgumentsEvent'
        Symfony\Component\HttpKernel\Event\FilterControllerEvent: 'Symfony\Component\HttpKernel\Event\ControllerArgumentsEvent'
        Symfony\Component\HttpKernel\Event\FilterResponseEvent: 'Symfony\Component\HttpKernel\Event\ResponseEvent'
        Symfony\Component\HttpKernel\Event\GetResponseEvent: 'Symfony\Component\HttpKernel\Event\RequestEvent'
        Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent: 'Symfony\Component\HttpKernel\Event\ViewEvent'
        Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent: 'Symfony\Component\HttpKernel\Event\ExceptionEvent'
        Symfony\Component\HttpKernel\Event\PostResponseEvent: 'Symfony\Component\HttpKernel\Event\TerminateEvent'
    Rector\Symfony\Rector\MethodCall\MakeDispatchFirstArgumentEventRector: ~
