services:
    # dependency-injection
    Rector\Rector\Dynamic\ArgumentAdderRector:
        $argumentChangesByMethodAndType:
            -
                class: Symfony\Component\DependencyInjection\ContainerBuilder
                method: addCompilerPass
                position: 2
                replacement_value: 0
