imports:
    # to cover prefixed rector and projects autoload - monorepo
    - { resource: '../../../../vendor/symplify/better-phpdoc-parser/src/config/services.yml' , ignore_errors: true }
    # to cover installed as dependency
    - { resource: '../../../../../../symplify/better-phpdoc-parser/src/config/services.yml' , ignore_errors: true }

    # rector/utils package
    - { resource: '../../../Utils/src/config/services.yml' }

    - { resource: 'services.yml' }
