imports:
    - { resource: 'external-services.yml' }

parameters:
    exclude_paths: [] # for FilesFinder

services:
    _defaults:
        # for "Rector\NodeTypeResolver\NodeTypeResolverFactory" standalone usage
        public: true
        autowire: true

    Rector\NodeTypeResolver\:
        resource: '../'
        exclude: '../{Contract,DependencyInjection/NodeTypeResolverKernel.php,DependencyInjection/NodeTypeResolverContainerFactory.php}'

    Rector\PhpParser\CurrentNodeProvider: ~

    Rector\Php\TypeAnalyzer: ~
    Rector\NodeTypeResolver\PhpDoc\NodeAnalyzer\DocBlockAnalyzer: ~
    Rector\Printer\BetterStandardPrinter: ~
    Rector\FileSystem\FilesFinder: ~
    Rector\Utils\BetterNodeFinder: ~

    # factory to remove dependency on CompilerPass and make install DX smoother
    Rector\NodeTypeResolver\NodeTypeResolver:
        factory: ['@Rector\NodeTypeResolver\NodeTypeResolverFactory', 'create']
