imports:
    - { resource: 'external-services.yml' }

parameters:
    exclude_paths: [] # for FilesFinder

services:
    _defaults:
        public: true
        autowire: true

    Rector\NodeTypeResolver\:
        resource: '../'
        exclude: '../{Contract}'

    Rector\PhpParser\CurrentNodeProvider: ~

    Rector\Php\TypeAnalyzer: ~
    Rector\NodeTypeResolver\PhpDoc\NodeAnalyzer\DocBlockAnalyzer: ~
    Rector\Printer\BetterStandardPrinter: ~
    Rector\FileSystem\FilesFinder: ~
    Rector\Utils\BetterNodeFinder: ~
