imports:
    - { resource: '../../packages/**/config/config.yml' }
    - { resource: 'services.yml' }
    - { resource: 'external-services.yml' }

parameters:
    exclude_paths: []
    exclude_rectors: []
    autoload_paths: []
