services:
    _defaults:
        public: true
        autowire: true

    # PhpParser - Parser
    PhpParser\Parser:
        factory: ['@Rector\Parser\ParserFactory', 'create']
    PhpParser\Lexer:
        factory: ['@Rector\Parser\LexerFactory', 'create']

    PhpParser\ParserFactory: ~
    PhpParser\BuilderFactory: ~
    PhpParser\NodeVisitor\CloningVisitor:

    # value resolver
    PhpParser\ConstExprEvaluator:
        factory: ['@Rector\NodeValueResolver\ConstExprEvaluatorFactory', 'create']

    Symfony\Component\Filesystem\Filesystem: ~

    # Symfony\Console
    Symfony\Component\Console\Style\SymfonyStyle: ~
    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput

    Symplify\PackageBuilder\FileSystem\FileSystem: ~
    Symplify\PackageBuilder\FileSystem\FinderSanitizer: ~

    # parameters
    Symplify\PackageBuilder\Parameter\ParameterProvider: ~

    # see https://github.com/symplify/packagebuilder#prevent-parameter-typos
    Symfony\Component\EventDispatcher\EventDispatcher: ~
    Symplify\PackageBuilder\EventSubscriber\ParameterTypoProofreaderEventSubscriber: ~
    Symplify\PackageBuilder\Parameter\ParameterTypoProofreader:
        $correctToTypos:
            exclude_paths:
                - '#exclude(d)?_(path(s)?|dir(s)?|file(s)?)#'
            autoload_paths:
                - '#autoload(d)?_(path(s)?|dir(s)?|file(s)?)#'
