services:
    _defaults:
        autowire: true
        public: true # for tests

    # PhpParser - Parser
    PhpParser\Parser:
        factory: ['@Rector\Parser\ParserFactory', 'create']
    PhpParser\Lexer:
        factory: ['@Rector\Parser\LexerFactory', 'create']
    PhpParser\ParserFactory: ~
    PhpParser\BuilderFactory: ~

    PhpParser\NodeVisitor\CloningVisitor:
    PhpParser\NodeVisitor\NameResolver:
        arguments:
            $options:
                # keep nodes the same, so the code can be saved without name changes
                'replaceNodes': false

    PhpParser\NodeTraverser: ~

    # Symfony\Console
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Input\InputInterface:
        alias: Symfony\Component\Console\Input\ArgvInput

    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface:
        alias: Symfony\Component\Console\Output\ConsoleOutput

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~

#    PhpCsFixer\Differ\UnifiedDiffer: ~
