services:
    _defaults:
        public: true
        autowire: true

    Rector\:
        resource: '../'
        exclude: '../{Node/Attribute.php,Rector/**/*Rector.php,Reporting/FileDiff.php,Testing,RectorDefinition,*/*/*Info.php,Configuration/Rector/*Recipe.php,Exception/*,DependencyInjection/CompilerPass/*}'

    # extra services
    Rector\Symfony\Rector\Form\Helper\FormTypeStringToTypeProvider: ~
