services:
    _defaults:
        autowire: true
        public: true # for tests

    Rector\:
        resource: '../'
        exclude: '../{Node/Attribute.php,Rector/Contrib,Rector/Dynamic,Rector/MagicDisclosure,Testing}'

    Rector\Rector\Contrib\Symfony\Form\Helper\FormTypeStringToTypeProvider: ~

    Rector\NodeTraverser\StandaloneTraverseNodeTraverser:
        # order matters, so the next NodeVisitor can work with previous' attributes
        calls:
            # adds FQN names for elements
            # adds previous, next and parent node via attribute
            # adds current class to all nodes via attribute
            # adds current method to all nodes via attribute
            # adds current namespace to all nodes via attribute (have to be before TypeResolver)
            - ['addNodeVisitors', [['@PhpParser\NodeVisitor\NameResolver', '@Rector\NodeVisitor\NodeConnector', '@Rector\NodeTypeResolver\NodeVisitor\ClassResolver', '@Rector\NodeTypeResolver\NodeVisitor\MethodResolver', '@Rector\NodeTypeResolver\NodeVisitor\NamespaceResolver']]]

            # adds type to variable and property nodes via attribute
#            - ['addNodeVisitor', ['@Rector\NodeTypeResolver\NodeVisitor\TypeNodeVisitor']]

            # adds types to caller of method calls and static calls via attribute (have to be after TypeResolver)
#            - ['addNodeVisitor', ['@Rector\NodeTypeResolver\NodeVisitor\CallerTypeNodeVisitor']]
