imports:
    - { resource: '../packages/**/config/config.yaml' }
    - { resource: 'services.yaml' }
    # only in local repository
    - { resource: '../utils/**/config/config.yaml', ignore_errors: true }

parameters:
    # processed paths
    paths: []
    exclude_paths: []
    exclude_rectors: []
    autoload_paths: []
    rector_recipe: []

    # importing FQN names
    auto_import_names: true
    # e.g. import \DateTime
    import_short_classes: true
    # e.g. /** @var \Some\ClassHere */
    import_doc_blocks: true

    # what PHP version is used for features, composer.json version, then local PHP version is used by default
    php_version_features: ~

    file_extensions:
        - 'php'
