imports:
    - { resource: '../packages/**/config/config.yaml' }
    - { resource: 'services.yaml' }
    # only in local repository
    - { resource: '../utils/**/config/config.yaml', ignore_errors: true }

parameters:
    exclude_paths: []
    exclude_rectors: []
    autoload_paths: []
