services:
    _defaults:
        autowire: true
        public: true # for tests

    Rector\DeprecationExtractor\:
        resource: '../../src'
        exclude: '../../src/{Deprecation/Deprecation.php,RectorGuess/RectorGuess.php}'
