services:
    _defaults:
        public: true
        autowire: true

    Rector\ConsoleDiffer\:
        resource: '../src'

    Rector\ConsoleDiffer\DifferAndFormatter:
        $differ: '@differ'

    Rector\ConsoleDiffer\MarkdownDifferAndFormatter:
        $markdownDiffer: '@markdownDiffer'

    # differ
    diffOutputBuilder:
        class: SebastianBergmann\Diff\Output\StrictUnifiedDiffOutputBuilder
        arguments:
            $options:
                'fromFile': 'Original'
                'toFile': 'New'

    differ:
        class: SebastianBergmann\Diff\Differ
        arguments:
            - '@diffOutputBuilder'

    # markdown differ
    markdownDiffOutputBuilder:
        class: SebastianBergmann\Diff\Output\UnifiedDiffOutputBuilder
        factory: ['@Rector\ConsoleDiffer\Diff\Output\CompleteUnifiedDiffOutputBuilderFactory', 'create']

    markdownDiffer:
        class: SebastianBergmann\Diff\Differ
        arguments:
            - '@markdownDiffOutputBuilder'

    Symplify\ConsoleColorDiff\Console\Formatter\ColorConsoleDiffFormatter: null
    Symplify\ConsoleColorDiff\Console\Output\ConsoleDiffer: null

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: null
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']
