# See https://github.com/shopware/shopware/blob/5.6/UPGRADE-5.6.md

imports:
    - { resource: '../elasticsearch-dsl/elasticsearch-dsl50.yaml' }

services:
    Rector\Shopware\Rector\MethodCall\ReplaceEnlightResponseWithSymfonyResponseRector: ~
    Rector\Rector\MethodCall\RenameMethodCallRector:
        Enlight_Controller_Response_Response:
            getHttpResponseCode: getStatusCode
            setHttpResponseCode: setStatusCode
            sendCookies: sendHeaders
            setBody: setContent
    Rector\Shopware\Rector\ClassConstFetch\ShopwareVersionConstsRector: ~
    Rector\Shopware\Rector\MethodCall\ShopRegistrationServiceRector: ~
