services:
    # scalar type hints, see https://github.com/nette/security/commit/84024f612fb3f55f5d6e3e3e28eef1ad0388fa56
    Rector\Rector\ClassMethod\AddReturnTypeDeclarationRector:
        Nette\Security\IAuthenticator:
            authenticate: 'Nette\Security\IIdentity'

        Nette\Security\IAuthorizator:
            isAllowed: 'bool'

        Nette\Security\Identity:
            getData: 'array'

        Nette\Security\IIdentity:
            getRoles: 'array'

        Nette\Security\User:
            getStorage: 'Nette\Security\IUserStorage'
            login: 'void'
            logout: 'void'
            isLoggedIn: 'bool'
            getIdentity: '?Nette\Security\IIdentity'
            getAuthenticator: '?Nette\Security\IAuthenticator'
            getAuthorizator: '?Nette\Security\IAuthorizator'
            getLogoutReason: '?int'
            getRoles: 'array'
            isInRole: 'bool'
            isAllowed: 'bool'

        Nette\Security\IUserStorage:
            isAuthenticated: 'bool'
            getIdentity: '?Nette\Security\IIdentity'
            getLogoutReason: '?int'

