parameters:
    dataDir: '%kernel.project_dir%/build'
    buildDir: '%kernel.project_dir%/..'

services:
    _defaults:
        public: true
        autowire: true

    Rector\Compiler\:
        resource: '../src'
        exclude:
            - '../src/Exception/*'
            - '../src/HttpKernel/*'

    Symfony\Component\Filesystem\Filesystem: null

    OndraM\CiDetector\CiDetector: null
