services:
    Rector\Nette\Rector\Application\InjectPropertyRector: ~
    Rector\Rector\Dynamic\ClassReplacerRector:
        $oldToNewClasses:
            'Nette\Config\Configurator': 'Nette\Configurator'
