services:
    _defaults:
        public: true
        autowire: true

    Rector\TypeDeclaration\:
        resource: '../src/'
        exclude: '../src/{Rector/**/*Rector.php,Exception,ValueObject/*}'
