services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Rector\Utils\PHPStanAttributeTypeSyncer\:
        resource: '../src'
        exclude:
            - '../src/ValueObject/*'
