imports:
    - { resource: '../../../../vendor/symplify/better-phpdoc-parser/src/config/services.yml' }

services:
    _defaults:
        autowire: true

    Rector\ReflectionDocBlock\:
        resource: '../'
