services:
    _defaults:
        autowire: true

    Rector\ReflectionDocBlock\:
        resource: '../'

    Rector\BetterReflection\TypesFinder\PhpDocumentor\NamespaceNodeToReflectionTypeContext: ~

    Symplify\BetterReflectionDocBlock\CleanDocBlockFactory: ~
    Symplify\BetterReflectionDocBlock\FixedSerializer: ~
