parameters:
    entity_repository_class: 'Doctrine\ORM\EntityRepository'
    entity_manager_class: 'Doctrine\ORM\EntityManager'

services:
    # order matters, this needs to be first to correctly detect parent repository
    Rector\Rector\Architecture\RepositoryAsService\ReplaceParentRepositoryCallsByRepositoryPropertyRector: ~
    Rector\Rector\Architecture\RepositoryAsService\MoveRepositoryFromParentToConstructorRector: ~
    Rector\Rector\Architecture\RepositoryAsService\ServiceLocatorToDIRector: ~
