services:
    Rector\Rector\Dynamic\NamespaceReplacerRector:
        $oldToNewNamespaces:
            'SyliusCoreBundle/Resources/config/serializer': 'SyliusAdminApiBundle/Resources/config/serializer'