# source: https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.0.md#upgrade-from-100-beta3-to-100

services:
    Rector\Rector\Dynamic\ClassReplacerRector:
        $oldToNewClasses:
            'DateTime': 'DateTimeInterface'
            'Sylius\Bundle\CoreBundle\Context\SessionAndChannelBasedCartContext': 'Sylius\Component\Core\Storage\CartStorageInterface'

    Rector\Rector\Dynamic\MethodNameReplacerRector:
            $perClassOldToNewMethods:
                'Sylius\Component\Core\Repository\OrderRepositoryInterface':
                    'count': 'countPlacedOrders'
                    'countByChannel': 'countFulfilledByChannel'

                'Sylius\Component\Product\Repository\ProductVariantRepositoryInterface':
                    'findByCodeAndProductCode': 'findByCodesAndProductCode'

                'Sylius\Component\Taxonomy\Model\TaxonInterface':
                    'getParents ': 'getAncestors'

    # @todo, use this and add new argument to a method
    Rector\Rector\Dynamic\ArgumentRector:
        $argumentByMethod:
            # findByCodeAndProductCode(string $code, string $productCode) was changed to findByCodesAndProductCode(array $codes, string $productCode)
            -
                type: 'add'
                class: 'Sylius\Component\Product\Repository\ProductVariantRepositoryInterface'
                method: 'findByCodesAndProductCode'
                position: 0 # as append
                typehint: 'array'
                property: '$codes'
                default_value: '[]'
                can_be_nul: false

    Rector\Rector\Dynamic\ParentTypehintedArgumentRector:
        $typehintForArgumentByMethodAndClass:
            # Constructor of Sylius\Bundle\CoreBundle\Context\SessionAndChannelBasedCartContext has been changed to use Sylius\Component\Core\Storage\CartStorageInterface
            'Sylius\Bundle\CoreBundle\Context\SessionAndChannelBasedCartContext':
                '__construct':
                    '$cartStorage': 'Sylius\Component\Core\Storage\CartStorageInterface'

    # @todo, use this and change typehint of return value
    Rector\Rector\Dynamic\ReturnTypehintedRector:
            $returnTypehintByMethod:
                # OrderInterface::getAdjustmentsRecursively and OrderItemInterface::getAdjustmentsRecursively return types changed from array to Collection
                'Sylius\Component\Order\Model\OrderInterface':
                    'getAdjustmentsRecursively':
                        'array': 'Doctrine\Common\Collections\Collection'

                'Sylius\Component\Order\Model\OrderItemInterface':
                    'getAdjustmentsRecursively':
                        'array': 'Doctrine\Common\Collections\Collection'

                # PrioritizedServiceRegistryInterface::all method return type changed from Zend's PriorityQueue to iterable
                'Sylius\Component\Registry\PrioritizedServiceRegistryInterface':
                    'all':
                        'Zend\Stdlib\PriorityQueue': 'iterable'