# @see https://www.tomasvotruba.cz/blog/2018/07/30/hidden-gems-of-php-packages-nette-utils/
services:
    Rector\Rector\Function_\FunctionToStaticCallRector:
        $functionToStaticCall:
            # filesystem
            file_get_contents: ['Nette\Utils\FileSystem', 'read']
            unlink: ['Nette\Utils\FileSystem', 'delete']
            rmdir: ['Nette\Utils\FileSystem', 'delete']

    # strings
    Rector\Nette\Rector\NotIdentical\StrposToStringsContainsRector: ~
    Rector\Nette\Rector\FuncCall\SubstrStrlenFunctionToNetteUtilsStringsRector: ~
    Rector\Nette\Rector\Identical\StartsWithFunctionToNetteUtilsStringsRector: ~
    Rector\Nette\Rector\Identical\EndsWithFunctionToNetteUtilsStringsRector: ~
    Rector\Nette\Rector\FuncCall\PregFunctionToNetteUtilsStringsRector: ~
    Rector\Nette\Rector\FuncCall\JsonDecodeEncodeToNetteUtilsJsonDecodeEncodeRector: ~
    Rector\Nette\Rector\FuncCall\FilePutContentsToFileSystemWriteRector: ~
