# see: https://gnugat.github.io/2015/09/23/phpunit-with-phpspec.html
services:
    # 1. first convert mocks
    Rector\PhpSpecToPHPUnit\Rector\MethodCall\PhpSpecMocksToPHPUnitMocksRector: ~
    Rector\PhpSpecToPHPUnit\Rector\MethodCall\PhpSpecPromisesToPHPUnitAssertRector: ~

    # 2. then methods
    Rector\PhpSpecToPHPUnit\Rector\ClassMethod\PhpSpecMethodToPHPUnitMethodRector: ~

    # 3. then the class itself
    Rector\PhpSpecToPHPUnit\Rector\Class_\PhpSpecClassToPHPUnitClassRector: ~
    Rector\PhpSpecToPHPUnit\Rector\Class_\AddMockPropertiesRector: ~

    Rector\PhpSpecToPHPUnit\Rector\ClassMethod\MockVariableToPropertyFetchRector: ~

    Rector\PhpSpecToPHPUnit\Rector\FileSystem\RenameSpecFileToTestFileRector: ~
