services:
    Rector\DeadCode\Rector\Stmt\RemoveDeadStmtRector: ~
    Rector\DeadCode\Rector\Array_\RemoveDuplicatedArrayKeyRector: ~
    Rector\DeadCode\Rector\Foreach_\RemoveUnusedForeachKeyRector: ~
    Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector: ~
