services:
    Rector\Rector\Function_\FunctionToMethodCallRector:
        $functionToMethodCall:
            'GuzzleHttp\json_decode': ['GuzzleHttp\Utils', 'jsonDecode']
            'GuzzleHttp\get_path': ['GuzzleHttp\Utils': 'getPath']
    Rector\Rector\StaticCall\StaticCallToFunctionRector:
        $staticCallToFunction:
            'GuzzleHttp\Utils::setPath': 'GuzzleHttp\set_path'
            'GuzzleHttp\Pool::batch': 'GuzzleHttp\Pool\batch'
