name: Rector Run

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    downgrade_php71:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: ./.github/workflows/scripts/downgrade_packages.sh 7.1
            # composer.json requires PHP 7.2, but we'll run 7.1 below, so set to ignore platform-check or it will fail
            -   run: composer config platform-check false

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.1
                    coverage: none

            # -   run: composer install --ignore-platform-req=php
            # -   run: composer phpstan
            # For testing, run downgraded Rector over its own src, for ALL sets!
            -   run: bin/rector process src --dry-run --set defluent
            -   run: bin/rector process src --dry-run --set action-injection-to-constructor-injection
            -   run: bin/rector process src --dry-run --set laravel-array-str-functions-to-static-call
            -   run: bin/rector process src --dry-run --set cakephp30
            -   run: bin/rector process src --dry-run --set cakephp34
            -   run: bin/rector process src --dry-run --set cakephp35
            -   run: bin/rector process src --dry-run --set cakephp36
            -   run: bin/rector process src --dry-run --set cakephp37
            -   run: bin/rector process src --dry-run --set cakephp38
            -   run: bin/rector process src --dry-run --set cakephp40
            -   run: bin/rector process src --dry-run --set cakephp41
            -   run: bin/rector process src --dry-run --set cakephp-fluent-options
            -   run: bin/rector process src --dry-run --set codeigniter-40
            -   run: bin/rector process src --dry-run --set code-quality
            -   run: bin/rector process src --dry-run --set coding-style
            -   run: bin/rector process src --dry-run --set coding-style-advanced
            -   run: bin/rector process src --dry-run --set contributte-to-symfony
            -   run: bin/rector process src --dry-run --set dead-classes
            -   run: bin/rector process src --dry-run --set dead-code
            -   run: bin/rector process src --dry-run --set doctrine25
            -   run: bin/rector process src --dry-run --set doctrine-behaviors-20
            -   run: bin/rector process src --dry-run --set doctrine-code-quality
            -   run: bin/rector process src --dry-run --set doctrine-common-20
            -   run: bin/rector process src --dry-run --set doctrine-dbal-210
            -   run: bin/rector process src --dry-run --set doctrine-dbal-30
            -   run: bin/rector process src --dry-run --set doctrine-gedmo-to-knplabs
            -   run: bin/rector process src --dry-run --set doctrine-id-to-uuid-step-1
            -   run: bin/rector process src --dry-run --set doctrine-id-to-uuid-step-2
            -   run: bin/rector process src --dry-run --set doctrine-id-to-uuid-step-3
            -   run: bin/rector process src --dry-run --set doctrine-id-to-uuid-step-4
            -   run: bin/rector process src --dry-run --set doctrine-id-to-uuid-step-5
            -   run: bin/rector process src --dry-run --set doctrine-repository-as-service
            -   run: bin/rector process src --dry-run --set doctrine-services
            -   run: bin/rector process src --dry-run --set downgrade-php71
            -   run: bin/rector process src --dry-run --set downgrade-php72
            -   run: bin/rector process src --dry-run --set downgrade-php73
            -   run: bin/rector process src --dry-run --set downgrade-php74
            -   run: bin/rector process src --dry-run --set downgrade-php80
            -   run: bin/rector process src --dry-run --set easy-admin-bundle20
            -   run: bin/rector process src --dry-run --set framework-extra-bundle-40
            -   run: bin/rector process src --dry-run --set framework-extra-bundle-50
            -   run: bin/rector process src --dry-run --set gmagick_to_imagick
            -   run: bin/rector process src --dry-run --set jms-decouple
            -   run: bin/rector process src --dry-run --set kdyby-events-to-contributte-event-dispatcher
            -   run: bin/rector process src --dry-run --set kdyby-to-symfony
            -   run: bin/rector process src --dry-run --set kdyby-translator-to-contributte-translation
            -   run: bin/rector process src --dry-run --set laravel50
            -   run: bin/rector process src --dry-run --set laravel51
            -   run: bin/rector process src --dry-run --set laravel52
            -   run: bin/rector process src --dry-run --set laravel53
            -   run: bin/rector process src --dry-run --set laravel54
            -   run: bin/rector process src --dry-run --set laravel55
            -   run: bin/rector process src --dry-run --set laravel56
            -   run: bin/rector process src --dry-run --set laravel57
            -   run: bin/rector process src --dry-run --set laravel58
            -   run: bin/rector process src --dry-run --set laravel60
            -   run: bin/rector process src --dry-run --set laravel-static-to-injection
            -   run: bin/rector process src --dry-run --set mockista-to-mockery
            -   run: bin/rector process src --dry-run --set monolog20
            -   run: bin/rector process src --dry-run --set mysql-to-mysqli
            -   run: bin/rector process src --dry-run --set naming
            -   run: bin/rector process src --dry-run --set nette-30
            -   run: bin/rector process src --dry-run --set nette-30-param-types
            -   run: bin/rector process src --dry-run --set nette-30-return-types
            -   run: bin/rector process src --dry-run --set nette-30-dependency-injection
            -   run: bin/rector process src --dry-run --set nette-code-quality
            -   run: bin/rector process src --dry-run --set nette-control-to-symfony-controller
            -   run: bin/rector process src --dry-run --set nette-forms-to-symfony
            -   run: bin/rector process src --dry-run --set nette-30-param-types
            -   run: bin/rector process src --dry-run --set nette-30-return-types
            -   run: bin/rector process src --dry-run --set nette-tester-to-phpunit
            -   run: bin/rector process src --dry-run --set nette-to-symfony
            -   run: bin/rector process src --dry-run --set nette-utils-code-quality
            -   run: bin/rector process src --dry-run --set order
            -   run: bin/rector process src --dry-run --set performance
            -   run: bin/rector process src --dry-run --set phalcon40
            -   run: bin/rector process src --dry-run --set phpexcel-to-phpspreadsheet
            -   run: bin/rector process src --dry-run --set phpspec30
            -   run: bin/rector process src --dry-run --set phpspec40
            -   run: bin/rector process src --dry-run --set phpspec-to-phpunit
            -   run: bin/rector process src --dry-run --set phpstan
            -   run: bin/rector process src --dry-run --set phpunit80-dms
            -   run: bin/rector process src --dry-run --set phpunit40
            -   run: bin/rector process src --dry-run --set phpunit50
            -   run: bin/rector process src --dry-run --set phpunit60
            -   run: bin/rector process src --dry-run --set phpunit70
            -   run: bin/rector process src --dry-run --set phpunit75
            -   run: bin/rector process src --dry-run --set phpunit80
            -   run: bin/rector process src --dry-run --set phpunit90
            -   run: bin/rector process src --dry-run --set phpunit91
            -   run: bin/rector process src --dry-run --set phpunit-code-quality
            -   run: bin/rector process src --dry-run --set phpunit-exception
            -   run: bin/rector process src --dry-run --set phpunit-injector
            -   run: bin/rector process src --dry-run --set phpunit-mock
            -   run: bin/rector process src --dry-run --set phpunit-specific-method
            -   run: bin/rector process src --dry-run --set phpunit-yield-data-provider
            -   run: bin/rector process src --dry-run --set php52
            -   run: bin/rector process src --dry-run --set php53
            -   run: bin/rector process src --dry-run --set php54
            -   run: bin/rector process src --dry-run --set php55
            -   run: bin/rector process src --dry-run --set php56
            -   run: bin/rector process src --dry-run --set php70
            -   run: bin/rector process src --dry-run --set php71
            -   run: bin/rector process src --dry-run --set php72
            -   run: bin/rector process src --dry-run --set php73
            -   run: bin/rector process src --dry-run --set php74
            -   run: bin/rector process src --dry-run --set php80
            -   run: bin/rector process src --dry-run --set php-code-sniffer30
            -   run: bin/rector process src --dry-run --set php-di-decouple
            -   run: bin/rector process src --dry-run --set privatization
            -   run: bin/rector process src --dry-run --set psr-4
            -   run: bin/rector process src --dry-run --set safe07
            -   run: bin/rector process src --dry-run --set solid
            -   run: bin/rector process src --dry-run --set swiftmailer60
            -   run: bin/rector process src --dry-run --set symfony26
            -   run: bin/rector process src --dry-run --set symfony28
            -   run: bin/rector process src --dry-run --set symfony30
            -   run: bin/rector process src --dry-run --set symfony31
            -   run: bin/rector process src --dry-run --set symfony32
            -   run: bin/rector process src --dry-run --set symfony33
            -   run: bin/rector process src --dry-run --set symfony34
            -   run: bin/rector process src --dry-run --set symfony40
            -   run: bin/rector process src --dry-run --set symfony41
            -   run: bin/rector process src --dry-run --set symfony42
            -   run: bin/rector process src --dry-run --set symfony43
            -   run: bin/rector process src --dry-run --set symfony44
            -   run: bin/rector process src --dry-run --set symfony50
            -   run: bin/rector process src --dry-run --set symfony50-types
            -   run: bin/rector process src --dry-run --set symfony-code-quality
            -   run: bin/rector process src --dry-run --set symfony-constructor-injection
            -   run: bin/rector process src --dry-run --set symfony-phpunit
            -   run: bin/rector process src --dry-run --set symfony-autowire
            -   run: bin/rector process src --dry-run --set twig112
            -   run: bin/rector process src --dry-run --set twig127
            -   run: bin/rector process src --dry-run --set twig134
            -   run: bin/rector process src --dry-run --set twig140
            -   run: bin/rector process src --dry-run --set twig20
            -   run: bin/rector process src --dry-run --set twig240
            -   run: bin/rector process src --dry-run --set twig-underscore-to-namespace
            -   run: bin/rector process src --dry-run --set type-declaration
            -   run: bin/rector process src --dry-run --set unwrap-compat
