name: Rector Run

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    downgrade_php71:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2
                    coverage: none

            -   run: composer install --no-dev
            -   run: vendor/bin/rector process src vendor --set downgrade-php71

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.1
                    coverage: none

            -   run: vendor/bin/rector process src --set dead-code
