name: Rector Run

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    downgrade_php71:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: ./.github/workflows/scripts/downgrade_packages.sh 7.1

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.1
                    coverage: none

            -   run: composer install --ignore-platform-req=php
            -   run: composer phpstan
