name: Rector Run

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    downgrade_php71:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: ./.github/workflows/scripts/downgrade_packages.sh 7.1

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.1
                    coverage: none

            # -   run: composer install --ignore-platform-req=php
            # -   run: composer phpstan
            # For testing, run downgraded Rector over its own src, for ALL sets!
            -   run: |
                    bin/rector process src --dry-run \
                        --set defluent \
                        --set action-injection-to-constructor-injection \
                        --set laravel-array-str-functions-to-static-call \
                        --set cakephp30 \
                        --set cakephp34 \
                        --set cakephp35 \
                        --set cakephp36 \
                        --set cakephp37 \
                        --set cakephp38 \
                        --set cakephp40 \
                        --set cakephp41 \
                        --set cakephp-fluent-options \
                        --set codeigniter-40 \
                        --set code-quality \
                        --set coding-style \
                        --set coding-style-advanced \
                        --set contributte-to-symfony \
                        --set dead-classes \
                        --set dead-code \
                        --set doctrine25 \
                        --set doctrine-behaviors-20 \
                        --set doctrine-code-quality \
                        --set doctrine-common-20 \
                        --set doctrine-dbal-210 \
                        --set doctrine-dbal-30 \
                        --set doctrine-gedmo-to-knplabs \
                        --set doctrine-id-to-uuid-step-1 \
                        --set doctrine-id-to-uuid-step-2 \
                        --set doctrine-id-to-uuid-step-3 \
                        --set doctrine-id-to-uuid-step-4 \
                        --set doctrine-id-to-uuid-step-5 \
                        --set doctrine-repository-as-service \
                        --set doctrine-services \
                        --set easy-admin-bundle20 \
                        --set framework-extra-bundle-40 \
                        --set framework-extra-bundle-50 \
                        --set gmagick_to_imagick \
                        --set jms-decouple \
                        --set kdyby-events-to-contributte-event-dispatcher \
                        --set kdyby-to-symfony \
                        --set kdyby-translator-to-contributte-translation \
                        --set laravel50 \
                        --set laravel51 \
                        --set laravel52 \
                        --set laravel53 \
                        --set laravel54 \
                        --set laravel55 \
                        --set laravel56 \
                        --set laravel57 \
                        --set laravel58 \
                        --set laravel60 \
                        --set laravel-static-to-injection \
                        --set mockista-to-mockery \
                        --set monolog20 \
                        --set mysql-to-mysqli \
                        --set naming \
                        --set nette-30 \
                        --set nette-30-param-types \
                        --set nette-30-return-types \
                        --set nette-30-dependency-injection \
                        --set nette-code-quality \
                        --set nette-control-to-symfony-controller \
                        --set nette-forms-to-symfony \
                        --set nette-30-param-types \
                        --set nette-30-return-types \
                        --set nette-tester-to-phpunit \
                        --set nette-to-symfony \
                        --set nette-utils-code-quality \
                        --set order \
                        --set performance \
                        --set phalcon40 \
                        --set phpexcel-to-phpspreadsheet \
                        --set phpspec30 \
                        --set phpspec40 \
                        --set phpspec-to-phpunit \
                        --set phpstan \
                        --set phpunit80-dms \
                        --set phpunit40 \
                        --set phpunit50 \
                        --set phpunit60 \
                        --set phpunit70 \
                        --set phpunit75 \
                        --set phpunit80 \
                        --set phpunit90 \
                        --set phpunit91 \
                        --set phpunit-code-quality \
                        --set phpunit-exception \
                        --set phpunit-injector \
                        --set phpunit-mock \
                        --set phpunit-specific-method \
                        --set phpunit-yield-data-provider \
                        --set php52 \
                        --set php53 \
                        --set php54 \
                        --set php55 \
                        --set php56 \
                        --set php70 \
                        --set php71 \
                        --set php72 \
                        --set php73 \
                        --set php74 \
                        --set php80 \
                        --set php-code-sniffer30 \
                        --set php-di-decouple \
                        --set privatization \
                        --set psr-4 \
                        --set safe07 \
                        --set solid \
                        --set swiftmailer60 \
                        --set symfony26 \
                        --set symfony28 \
                        --set symfony30 \
                        --set symfony31 \
                        --set symfony32 \
                        --set symfony33 \
                        --set symfony34 \
                        --set symfony40 \
                        --set symfony41 \
                        --set symfony42 \
                        --set symfony43 \
                        --set symfony44 \
                        --set symfony50 \
                        --set symfony50-types \
                        --set symfony-code-quality \
                        --set symfony-constructor-injection \
                        --set symfony-phpunit \
                        --set symfony-autowire \
                        --set twig112 \
                        --set twig127 \
                        --set twig134 \
                        --set twig140 \
                        --set twig20 \
                        --set twig240 \
                        --set twig-underscore-to-namespace \
                        --set type-declaration \
                        --set unwrap-compat
