name: Rector CI

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    rector-ci:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none
            -   run: composer install --no-progress
            -   run: composer rector-ci

            -
                name: Check for modified files
                id: git-check
                run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

            -
                name: Commit rector
                if: steps.git-check.outputs.modified == 'true'
                run: |
                  git config --global user.name 'Rector'
                  git config --global user.email 'rector@actions.github.com'
                  git checkout "${GITHUB_REF:11}"
                  git commit -am "Rector fixes"
                  git push
