name: Rector CI

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    rector-ci:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v2
                with:
                    ref: ${{ github.event.pull_request.head.ref }}

            -
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer rector-ci

            -
                name: Check for modified files
                id: git-check
                run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

            -
                name: Commit rector
                # Due to limitations, it does not work with PRs from forked repositories, forks has to fix manually
                if: steps.git-check.outputs.modified == 'true' && github.event.pull_request.head.repo.full_name == github.repository
                run: |
                  git config --global user.name 'rectorphp'
                  git config --global user.email 'rectorphp@users.noreply.github.com'
                  git commit -am "Rector fixes"
                  git push
