name: Standalone Run

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    standalone_run:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2
                    coverage: none # disable xdebug, pcov
                    extensions: "intl"

            # Run standalone install in non-root package, ref https://github.com/rectorphp/rector/issues/732
            -   run: |
                    # wait till packagist gets information about new branches
                    sleep 30

                    # 1. install locally
                    mkdir test-paths
                    cd test-paths

                    mkdir rector-dir
                    # get branch name see https://stackoverflow.com/a/61699863/1348344
                    composer require rector/rector:dev-${GITHUB_REF#refs/heads/}#${GITHUB_SHA} -d rector-dir --no-progress --ansi
                    mkdir symfony-demo-dir
                    composer create-project symfony/symfony-demo symfony-demo-dir --dev --no-progress --ansi

                    # missing for some reason
                    composer require doctrine/doctrine-fixtures-bundle -d symfony-demo-dir --no-progress --ansi
                    composer dump-autoload --no-dev -d symfony-demo-dir --ansi

                    # 2. run an another project
                    rector-dir/vendor/bin/rector --ansi

                    cd symfony-demo-dir
                    ../rector-dir/vendor/bin/rector --ansi

                    # autoload errors due to remove --dev and mixed dependencies in /src and /tests
                    ../rector-dir/vendor/bin/rector process src --set code-quality --ansi
