services:
    Rector\TypeDeclaration\Rector\FunctionLike\ParamTypeDeclarationRector: ~
    Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector: ~
    Rector\TypeDeclaration\Rector\Closure\AddClosureReturnTypeRector: ~
