services:
    Rector\Php\Rector\FunctionLike\ParamTypeDeclarationRector: ~
    Rector\Php\Rector\FunctionLike\ReturnTypeDeclarationRector: ~
    Rector\TypeDeclaration\Rector\Function_\AddFunctionReturnTypeRector: ~
